language: node_js

node_js:
  - "node"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g npm typescript

install:
  - npm install --ignore-scripts
  - npm run prepublishOnly
  - npm run postinstall

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
- master