language: node_js

node_js:
  - "node"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g npm

install: 
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
- master